# Generated by Django 2.1.9 on 2020-02-04 21:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathers_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=70)),
                ('aadhaar_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Enter a valid aadhaar number.', regex='[0-9]{12}')])),
                ('contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number.', regex='^[789][0-9]{9}$')])),
                ('category_of_crime', models.CharField(choices=[('1', 'Robbery'), ('2', 'Murder'), ('3', 'Kidnapping'), ('4', 'Child Abuse'), ('5', 'Domestic Abuse'), ('6', 'Missing'), ('7', 'Other')], max_length=1)),
                ('place_of_crime', models.CharField(max_length=128)),
                ('date_time_of_crime', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('other_details', models.TextField()),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
